@startuml
skinparam class {
    BackgroundColor<<Dominio>> Wheat
    BorderColor<<Dominio>> Tomato
}

class ImagenMemoria {
    + ejecutarMutacion(mutacion: Mutacion)
}
ImagenMemoria ..> Mutacion: ejecuta >

interface Mutacion {
    aplicarA(sistema: Any)
}
class Banco <<Dominio>> {
}
class Cuenta <<Dominio>> {
    + id: String
    + nombre: String
    + balance: Monto
}
Banco "1" *--> "0..*" Cuenta

class Deposito implements Mutacion {
    + idCuenta: String
    + monto: Monto
    + aplicarA(banco: Banco)
}
Deposito ..> Cuenta: increments balance >
note bottom of Deposito
    banco[idCuenta].balance += monto
end note

@enduml